# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ["load_kaggle_key", "download_flickr8k_from_kaggle"]

# %% ../nbs/00_core.ipynb 4
from torch_snippets import *


# %% ../nbs/00_core.ipynb 5
def load_kaggle_key(kaggle_json_path):
    kaggle_json = read_json(kaggle_json_path)
    os.environ["KAGGLE_USERNAME"] = kaggle_json["username"]
    os.environ["KAGGLE_KEY"] = kaggle_json["key"]
    Info(f"Loaded key from {kaggle_json_path}")


def download_flickr8k_from_kaggle(kaggle_json_path, download_folder_location):
    load_kaggle_key(kaggle_json_path)
    import kaggle

    kaggle.api.authenticate()
    if exists(f"{download_folder_location}/captions.txt"):
        Info(f"Data is already downloaded at {download_folder_location}")
        return
    with notify_waiting("Downloading flickr8k data..."):
        kaggle.api.dataset_download_files(
            "adityajn105/flickr8k", path=download_folder_location, unzip=True
        )
